version: "3.2"

services:
  pynx584:
    container_name: pynx584
    image: ghcr.io/kk7ds/pynx584
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./config:/config
    build:
      dockerfile: Dockerfile
    command:
      - --baudrate
      - 9600
      - --config
      - /config/alarm.ini
      - --serial
      - /dev/ttyUSB0
    restart: unless-stopped
    ports:
      - 5007:5007
